### ISSUE TITLE
Undeclared Identifier: "product"

### ISSUE THREAD

**Issue by KD33** [bovender/ExcelAddinInstaller#5]
Hello, 
I'm trying to work through your most basic scenario.  Whenever I try to compile addin-installer, I get an error pointing to Line 1 of inc/setup.iss
[ISPP] Undeclared identifier: "product".

I've tried declaring public before product in the config.iss file, but no luck.  

Edit: I was able to work around it by hardcoding the values required in inc/setup, but would still like to know why it did not work

Thanks

**Comment by bovender** [comment]
Can't look into this right now because I need to re-install InnoSetup on a new system, but the server jrsoftware.org has been down the past couple of days.

**Comment by bovender** [comment]
It occurs to me that you might not have the InnoSetup preprocessor installed? Could that be the explanation for the error?

BTW jrsoftware.org is back up again.

**Comment by KD33** [comment]
Just looked through the notes for 5.6.1.  It looks like the InnoSetup preprocessor is included in the installation as of version 5.4.  I also re-installed InnoSetup.  There is an option to install the preprocessor with the installation, which I checked.

**Comment by bovender** [comment]
OK. `PRODUCT` is defined in `config.iss`. Did you actually copy `config-dist/config.dist.iss` to `config.iss` in the base directory?

I realized that `addin-installer.iss` contains this statement:

    [Setup]
    #ifexist "config.iss"        
      #include "config.iss"
    #endif

This `#ifexist` statement could be the reason why you get the error "undeclared identifier: product" rather than a more meaningful "config.iss not found".

**Comment by bovender** [comment]
@KD33 Feel free to re-open the issue if that did not fix it!
